spring:
  application:
    name: ensitech
  profiles:
    # On active le profil 'local' pour le développement en local
    active: local
  datasource:
    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8084